# Generated by Django 4.2.1 on 2023-05-21 12:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('image', models.ImageField(default='base/Service.jpg', upload_to='service', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('disabled', 'Скрыто'), ('published', 'Опубликовано')], default='draft', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
