# Generated by Django 4.2.1 on 2023-05-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0009_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveBigIntegerField(verbose_name='Номер заказа')),
                ('first_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('add_address', models.CharField(max_length=250, null=True, verbose_name='Комментарий')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('total_amount', models.PositiveBigIntegerField(verbose_name='Сумма заказа')),
                ('cart_data', models.JSONField(verbose_name='JSON корзины')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'Комплектуется'), ('on_the_way', 'Доставляется'), ('delivered', 'Доставлено'), ('refund', 'Возврат')], default='new', max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(verbose_name='Количество товара')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена на момент заказа')),
                ('status', models.CharField(choices=[('packed', 'Укомплектовано'), ('in_queue', 'В очереди')], default='in_queue', max_length=15, verbose_name='Статус')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='Номер заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
