# Generated by Django 4.2.1 on 2023-05-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='base/slider.jpg', upload_to='slider', verbose_name='Изображение')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.CharField(max_length=100, verbose_name='Текст под заголовком')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('button_name', models.CharField(max_length=100, verbose_name='Название кнопки')),
                ('queue', models.PositiveSmallIntegerField(verbose_name='Очередь')),
                ('draft', models.BooleanField(default=True, verbose_name='Черновик')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
