# Generated by Django 4.2.1 on 2023-05-11 11:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_best_seller_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Характеристики'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Specifications',
        ),
    ]
