# Generated by Django 4.2.1 on 2023-05-24 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuscomment',
            name='user',
        ),
        migrations.AddField(
            model_name='contactuscomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
