# Generated by Django 4.2.1 on 2023-05-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_contactuscomment_user_contactuscomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='base/Banner.jpg', upload_to='banner', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='base/Slider.jpg', upload_to='slider', verbose_name='Изображение'),
        ),
    ]
